Repository HomeFoodFighter/Server, pull requests merged in 2023-07, with the labels that each got.

#11 [MOD] error 코드 수정
  config/baseResponse.js
Labels: minhee

#21 [ADD]recipeDao에서 여러 쿼리 추가
  src/app/recipe/recipeController.js
  src/app/recipe/recipeDao.js
  src/app/recipe/recipeProvider.js
  src/app/recipe/recipeRoute.js
Labels: minhee

#23 [MOD]jwt 토큰 형식에 맞게 userid 변경
  src/app/recipe/recipeController.js
  src/app/recipe/recipeRoute.js
Labels: minhee

#24 [MOD] API.15 URI 수정
  config/baseResponse.js
  src/app/recipe/recipeController.js
  src/app/recipe/recipeDao.js
  src/app/recipe/recipeProvider.js
  src/app/recipe/recipeRoute.js
Labels: minhee

#25 [FEAT] API.15레시피 상세 페이지 조회
  src/app/recipe/recipeController.js
  src/app/recipe/recipeDao.js
Labels: minhee

#27 [ADD] 인기레시피 조회 추가
  src/app/recipe/recipeController.js
  src/app/recipe/recipeDao.js
  src/app/recipe/recipeProvider.js
  src/app/recipe/recipeRoute.js
Labels: minhee

#28 [FEAT] 등록되지 않은 이메일은 오류 메시지 출력 기능 구현
  config/baseResponse.js
  src/app/recipe/recipeController.js
  src/app/recipe/recipeRoute.js
  src/app/user/userService.js
Labels: JJong, done!

#30 [FEAT] 아이디/비밀번호 찾기 기능 구현
  config/baseResponse.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userService.js
Labels: JJong, done!

#39 [FEAT] 내 레시피 조회 기능 구현
  src/app/mypage/mypageController.js
  src/app/mypage/mypageDao.js
  src/app/mypage/mypageProvider.js
  src/app/mypage/mypageRoute.js
Labels: JJong, done!

#41 [MOD] recipeRoute.js에서 refrigerator.possibleRecipe를 recipe.possibleRe…
  src/app/mypage/mypageController.js
  src/app/mypage/mypageRoute.js
  src/app/recipe/recipeRoute.js
  src/app/user/userController.js
  src/app/user/userProvider.js
Labels: JJong, done!

#42 [FEAT] 16번 라우트 추가
  src/app/recipe/recipeRoute.js
Labels: minhee

#43 [ADD] calendar 폴더 생성
  src/app/calendar/calendarController.js
  src/app/calendar/calendarDao.js
  src/app/calendar/calendarProvider.js
  src/app/calendar/calendarRoute.js
  src/app/calendar/calendarService.js
  src/app/recipe/recipeController.js
  src/app/recipe/recipeRoute.js
Labels: minhee

#44 [FEAT] 내가 쓴 리뷰 조회API 기능 구현
  src/app/mypage/mypageController.js
  src/app/mypage/mypageDao.js
  src/app/mypage/mypageProvider.js
Labels: JJong, done!

#45 [FEAT] api.16 주간캘린더 조회 완성
  config/express.js
  src/app/calendar/calendarController.js
  src/app/calendar/calendarDao.js
  src/app/calendar/calendarProvider.js
Labels: minhee

#49 [FEAT] 회원 탈퇴 API 기능 구현
  src/app/mypage/mypageController.js
  src/app/mypage/mypageDao.js
  src/app/mypage/mypageRoute.js
  src/app/mypage/mypageService.js
Labels: JJong, done!

#51 [ADD] userController.js에 로그인 API 코드에 탈퇴한 유저 로그인 차단 기능 코드 추가
  config/baseResponse.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
Labels: JJong, done!

#52 [MOD] API.18 캘린더에서 직접 입력하기 미완성
  config/baseResponse.js
  src/app/calendar/calendarController.js
  src/app/calendar/calendarDao.js
  src/app/calendar/calendarRoute.js
  src/app/calendar/calendarService.js
Labels: minhee

#53 [FEAT] API.18 완성
  src/app/calendar/calendarController.js
Labels: minhee

#54 [FEAT] 레시피 찜하기 구현
  config/baseResponse.js
  src/app/recipe/recipeController.js
  src/app/recipe/recipeDao.js
  src/app/recipe/recipeRoute.js
  src/app/recipe/recipeService.js
Labels: minhee

#55 [ADD] 로그아웃 코드 추가
  config/express.js
  package.json
  src/app/mypage/mypageController.js
  src/app/mypage/mypageRoute.js
  src/app/mypage/mypageService.js
  src/app/user/userController.js
  src/app/user/userRoute.js
Labels: JJong

#56 [FEAT] 찜한 레시피 조회
  config/baseResponse.js
  src/app/mypage/mypageController.js
  src/app/mypage/mypageDao.js
  src/app/mypage/mypageProvider.js
  src/app/mypage/mypageRoute.js
  src/app/recipe/recipeDao.js
  src/app/recipe/recipeRoute.js
Labels: minhee

#57 [ERR] 오류 발생
  src/app/calendar/calendarController.js
  src/app/calendar/calendarDao.js
  src/app/calendar/calendarProvider.js
  src/app/calendar/calendarRoute.js
  src/app/calendar/calendarService.js
Labels: minhee

#59 [FEAT] API.17 찜으로 캘린더 추가하기
  src/app/calendar/calendarController.js
  src/app/calendar/calendarDao.js
Labels: minhee

#60 [MOD] 쿼리 수정
  src/app/recipe/recipeDao.js
Labels: minhee

#61 [MOD] API.9 수정
  src/app/mypage/mypageDao.js
Labels: minhee

#64 [FEAT] API.19 레시피 찜 취소하기
  config/baseResponse.js
  src/app/recipe/recipeController.js
  src/app/recipe/recipeDao.js
  src/app/recipe/recipeRoute.js
  src/app/recipe/recipeService.js
Labels: minhee

#66 [MOD] mypageDao.js의 selectMyRecipes코드 수정
  src/app/mypage/mypageDao.js
Labels: JJong, done!
